FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y systemd && \
    apt-get clean
COPY ./mango /usr/bin/mango
COPY ./packaging/systemd/mango.service /etc/systemd/system/
COPY ./test/mockup/inventory /opt/mango/inventory/

RUN systemctl enable mango.service

CMD ["/lib/systemd/systemd"]
