# Compose file to set up the following services for local testing:
  # - grafana
  # - prometheus
  # - loki
  # - promtail
# based heavily on:
# https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
# https://raw.githubusercontent.com/grafana/loki/v2.8.0/production/docker-compose.yaml
#
# NOTE:
# this compose file should be invoked with `--podman-run-args="--systemd=true"`

version: "3.9"

networks:
  mango:
    driver: bridge

services:
  mango-ubuntu-2204:
    image: mango-test-ubuntu:latest
    hostname: testbox-mango-ubuntu
    restart: unless-stopped
    ports:
      - "9555"
    networks:
      - mango
    volumes:
      - ./mango:/usr/bin/mango
      - ./mh:/usr/bin/mh
      - ./test/mockup/inventory:/opt/mango/inventory/:ro
      - ./test/mockup/testbox-mango-ubuntu-mount/:/testbox-mango-ubuntu-mount/

  mango-archlinux:
    image: mango-test-arch:latest
    hostname: testbox-mango-arch
    restart: unless-stopped
    ports:
      - "9555"
    networks:
      - mango
    volumes:
      - ./mango:/usr/bin/mango
      - ./mh:/usr/bin/mh
      - ./test/mockup/inventory/:/opt/mango/inventory/:ro
      - ./test/mockup/testbox-mango-arch-mount/:/testbox-mango-arch-mount/

  unenrolled-archlinux:
    image: mango-test-arch:latest
    hostname: testbox-unenrolled-arch
    restart: unless-stopped
    ports:
      - "9555"
    networks:
      - mango
    volumes:
      - ./mango:/usr/bin/mango
      - ./mh:/usr/bin/mh
      - ./test/mockup/inventory/:/opt/mango/inventory/:ro
      - ./test/mockup/testbox-unenrolled-arch-mount/:/testbox-unenrolled-arch-mount/
