#!/usr/bin/env bash

FILE="/tmp/$(basename ${0%/*})-$$"
# capture ordering info
echo "{{ .Mango.Metadata.ModuleName }}" >> /tmp/mango-dependency-testing

echo "Dumping environment to ${FILE}"

/usr/bin/env > "${FILE}"
