#!env bash

FILE="/tmp/$(basename ${0%/*})-$$"
# capture ordering info
echo "{{ .Mango.Metadata.ModuleName }}" >> /tmp/mango-dependency-testing

# background process to attempt triggering some reloads while run is in progress
bash -c 'for i in {1..3}; do sleep 2; systemctl reload mango.service; done' &

echo "[$(date +%s)] Sleeping for 15s" > "${FILE}"
sleep 15
echo "[$(date +%s)] Done" > "${FILE}"
