#!env bash

FILE="/tmp/$(basename ${0%/*})-$$"
# capture ordering info
echo "{{ .Mango.Metadata.ModuleName }}" >> /tmp/mango-dependency-testing

echo "[$(date +%s)] Sleeping for 1m" > "${FILE}"
sleep 60
echo "[$(date +%s)] Done" > "${FILE}"
