#!/usr/bin/env bash

touch "/tmp/$(basename {{ .Mango.Metadata.ModuleName }}).skip-please"

echo "{{ .Mango.Metadata.ModuleName }} apply" >> "/tmp/$(basename {{ .Mango.Metadata.ModuleName }}).script-execs"
