#!/usr/bin/env bash

FILE="/tmp/$(basename ${0%/*})-$$"

cat > ${FILE} <<EOF
    Testing templating!
    Printing all variables available, via template
    -------------------
    Printing host variables:
    {{- range $k, $v := .Mango.HostVars }}
    {{ $k }}: {{ $v }}
    {{- end }}
    -------------------
    Printing module variables:
    {{- range $k, $v := .Mango.ModuleVars }}
    {{ $k }}: {{ $v }}
    {{- end }}
    -------------------
    Printing all variables (merged, where module variables override host variables):
    {{- range $k, $v := .Mango.Vars }}
    {{ $k }}: {{ $v }}
    {{- end }}
    -------------------
    Printing all Mango metadata:
    Enrollment status: {{ .Mango.Metadata.Enrolled }}
    Run ID: {{ .Mango.Metadata.RunID }}
    Manager Name: {{ .Mango.Metadata.ManagerName }}
    Inventory Path: {{ .Mango.Metadata.InventoryPath }}
    Hostname: {{ .Mango.Metadata.Hostname }}
    -------------------
    Done.
EOF
